name: Next.js Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # You can change this to the desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
